"""Build Worker data from the latest crawl:
 - app/worker/src/receipts-data.js: RECEIPTS_META (coverage, new this week, sources) + RECEIPTS = page 1 of skips (bundled)
 - receipts/kv/bulk.json: every receipt in 256 shards (c:<id[0:2]>), skip pages (s:<n>), meta -> CRAWL_KV
 - receipts/kv/changed.json: only keys whose value changed since the last upload (keeps KV writes far under 1k/day)
Prints the one-line coverage summary as the last line."""
import json, os, sys, collections, hashlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from crawl_probe import norm_url, mainnet_policy
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KV = os.path.join(ROOT, "kv"); os.makedirs(KV, exist_ok=True)
PAGE = 500
FEATURED = "b5e13e8271"  # README's featured case while it is still a skip
name = open(os.path.join(ROOT, "latest.txt")).read().strip()
rs = [mainnet_policy(json.loads(l)) for l in open(os.path.join(ROOT, name))]  # 0.14.0: testnet / non-canonical USDC pays -> skip
keep = ["id", "url", "claimed_price_usd", "quoted_price_usd", "pay_to", "verdict", "reason", "timestamp", "source_list",
        "also_listed_in", "check_type", "method", "http_status", "network", "listed_network", "listed_pay_to", "free_trial_remaining"]
rs = [{k: r.get(k) for k in keep if r.get(k) not in (None, [])} | {"id": r["id"], "url": r["url"], "verdict": r["verdict"]} for r in rs]
for r in rs:
    r.setdefault("reason", ""); r.setdefault("timestamp", "")
# previous run -> new this week (by normalized URL)
prev_name = open(os.path.join(ROOT, "previous.txt")).read().strip() if os.path.exists(os.path.join(ROOT, "previous.txt")) else ""
prev = set()
if prev_name and prev_name != name and os.path.exists(os.path.join(ROOT, prev_name)):
    prev = {json.loads(l).get("norm_url") or norm_url(json.loads(l)["url"]) for l in open(os.path.join(ROOT, prev_name))}
cur = {norm_url(r["url"]) for r in rs}
new = cur - prev if prev else set()
# skips, clearest first: listing-vs-402 mismatches, then missing 402, then the rest
rank = lambda r: (0 if "network mismatch" in r["reason"] else 1 if "payTo differs" in r["reason"] else 2 if "price mismatch" in r["reason"]
                  else 3 if "asset mismatch" in r["reason"] else 4 if "no 402" in r["reason"] else 5, r["url"])
skips = sorted((r for r in rs if r["verdict"] == "skip"), key=rank)
if not any(r["id"] == FEATURED for r in skips):
    assert skips, "crawl has no skip receipts"
    FEATURED = skips[0]["id"]
else:  # keep it on page 1
    skips = [r for r in skips if r["id"] == FEATURED] + [r for r in skips if r["id"] != FEATURED]
pages = [skips[i:i + PAGE] for i in range(0, len(skips), PAGE)] or [[]]
counts = collections.Counter(r["verdict"] for r in rs)
sources = json.load(open(os.path.join(ROOT, "crawl", "sources.json"))) if os.path.exists(os.path.join(ROOT, "crawl", "sources.json")) else {}
meta = {"crawled_at": min(r["timestamp"] for r in rs if r["timestamp"]), "crawl_finished_at": max(r["timestamp"] for r in rs if r["timestamp"]), "file": name,
        "endpoints_covered": len(rs), "new_this_week": len(new), "previous_run": prev_name or None, "previous_covered": len(prev) or None,
        "total": len(rs), "skip": counts["skip"], "pay": counts["pay"], "recheck": counts["recheck"],
        "lists": dict(collections.Counter(r["source_list"] for r in rs)),
        "listed_in": dict(collections.Counter(s for r in rs for s in [r["source_list"]] + r.get("also_listed_in", []))),
        "sources": {k: {kk: v.get(kk) for kk in ("ok", "skipped", "items", "note", "error") if v.get(kk) is not None} for k, v in sources.items()},
        "featured_id": FEATURED, "skip_pages": len(pages), "page_size": PAGE, "check_type": "self-checked",
        "dedupe": "normalized URL (lower-case scheme/host, no default port/fragment/trailing slash, sorted query)",
        "method": "One unpaid GET/POST per listed URL (listing's example params only if the bare URL 4xx'd), 5s timeout, SSRF-gated, at most 3 requests in flight per host. Never pays."}
out = os.path.join(ROOT, "..", "app", "worker", "src", "receipts-data.js")
with open(out, "w") as f:
    f.write("// GENERATED by receipts/scripts/build_worker_data.py from receipts/" + name + ". Do not edit.\n")
    f.write("// RECEIPTS = page 1 of /v1/skips; every receipt lives in the CRAWL_KV namespace (c:<id[0:2]> shards).\n")
    f.write("export const RECEIPTS_META = " + json.dumps(meta) + ";\n")
    f.write("export const RECEIPTS = " + json.dumps(pages[0], separators=(",", ":")) + ";\n")
shards = collections.defaultdict(dict)
for r in rs: shards[r["id"][:2]][r["id"]] = r
bulk = [{"key": "c:" + k, "value": json.dumps(v, separators=(",", ":"))} for k, v in sorted(shards.items())]
bulk += [{"key": f"s:{i + 1}", "value": json.dumps(p, separators=(",", ":"))} for i, p in enumerate(pages)]
bulk.append({"key": "meta", "value": json.dumps(meta, separators=(",", ":"))})
assert max(len(b["value"]) for b in bulk) < 20_000_000
json.dump(bulk, open(os.path.join(KV, "bulk.json"), "w"))
man_path = os.path.join(KV, "uploaded.json")
uploaded = json.load(open(man_path)) if os.path.exists(man_path) else {}
h = lambda v: hashlib.sha256(v.encode()).hexdigest()
changed = [b for b in bulk if uploaded.get(b["key"]) != h(b["value"])]
json.dump(changed, open(os.path.join(KV, "changed.json"), "w"))
json.dump({b["key"]: h(b["value"]) for b in bulk}, open(os.path.join(KV, "pending.json"), "w"))
print(out, os.path.getsize(out), "kv keys", len(bulk), "changed", len(changed), "largest shard", max(len(b["value"]) for b in bulk if b["key"].startswith("c:")))
print(f"COVERAGE covered={len(rs)} new_this_week={len(new)} pay={counts['pay']} skip={counts['skip']} recheck={counts['recheck']} sources_ok={sum(1 for v in sources.values() if v.get('ok'))}/{len(sources)}")
